export const matesData = [
    {
      id: 1,
      name: "Anurag Kashyap",
      role: "Full Stack Developer",
      location: "Raipur",
      image: "https://plus.unsplash.com/premium_photo-1671656349322-41de944d259b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      skills: ["React", "Node.js", "Express", "MongoDB"],
      bio: "A passionate developer with a love for creating intuitive user interfaces.",
      categories: ["Software", "Creativity"],
    },
    {
      id: 2,
      name: "Shreya Singh",
      role: "Python | MERN Developer",
      location: "Bilaspur",
      image: "https://images.unsplash.com/photo-1684966610091-f6beda2d025a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHByb2ZpbGUlMjBpbWFnZXxlbnwwfHwwfHx8MA%3D%3D",
      skills: ["Python", "Django", "React", "API Development"],
      bio: "An enthusiastic programmer skilled in Python and modern web technologies.",
      categories: ["Artificial Intelligence"],
    },
    {
      id: 3,
      name: "Mehul Sahu",
      role: "MERN Stack Developer",
      location: "Chhattisgarh",
      image: "https://images.unsplash.com/photo-1669475535978-7479ef74e14f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHByb2ZpbGUlMjBpbWFnZXxlbnwwfHwwfHx8MA%3D%3D",
      skills: ["JavaScript", "MongoDB", "Express", "React"],
      bio: "A dedicated MERN stack developer with a knack for backend systems.",
      categories: ["Web 3", "Finance"],
    },
    {
      id: 4,
      name: "Priyanshu Tandan",
      role: "Full Stack Web Developer",
      location: "Bhilai",
      image: "https://images.unsplash.com/photo-1505033575518-a36ea2ef75ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHByb2ZpbGUlMjBpbWFnZXxlbnwwfHwwfHx8MA%3D%3D",
      skills: ["HTML", "CSS", "React", "Node.js"],
      bio: "Creative and efficient in crafting scalable web solutions.",
      categories: ["E-Commerce", "Marketing"],
    },
    {
      id: 5,
      name: "Yash Chandrakar",
      role: "MERN Stack Developer",
      location: "Chhattisgarh",
      image: "https://images.unsplash.com/photo-1722322426803-101270837197?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHByb2ZpbGUlMjBpbWFnZXxlbnwwfHwwfHx8MA%3D%3D",
      skills: ["React", "Redux", "Express", "MongoDB"],
      bio: "Focused on delivering high-quality, robust web applications.",
      categories: ["Nonprofits", "Education"],
    },
    {
      id: 6,
      name: "Aditi Sharma",
      role: "Data Scientist",
      location: "Delhi",
      image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=60",
      skills: ["Python", "TensorFlow", "Pandas"],
      bio: "Transforming data into actionable insights for better decision-making.",
      categories: ["Artificial Intelligence", "Finance"],
    },
    {
      id: 7,
      name: "Rohan Gupta",
      role: "Blockchain Developer",
      location: "Bangalore",
      image: "https://images.unsplash.com/photo-1528459103400-df0f3f523846?w=500&auto=format&fit=crop&q=60",
      skills: ["Solidity", "Smart Contracts", "Ethereum", "JavaScript"],
      bio: "Passionate about decentralized technologies and blockchain innovation.",
      categories: ["Web 3", "Finance"],
    },
    {
      id: 8,
      name: "Ishaan Bose",
      role: "Marketing Strategist",
      location: "Mumbai",
      image: "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=500&auto=format&fit=crop&q=60",
      skills: ["SEO", "Content Creation", "Social Media Marketing"],
      bio: "Helping brands grow by creating impactful marketing campaigns.",
      categories: ["Marketing", "Travel"],
    },
    {
      id: 9,
      name: "Nisha Patel",
      role: "UI/UX Designer",
      location: "Ahmedabad",
      image: "https://images.unsplash.com/photo-1506812574058-fc75fa93fead?w=500&auto=format&fit=crop&q=60",
      skills: ["Figma", "Sketch", "Adobe XD", "HTML/CSS"],
      bio: "Designing user-friendly interfaces with a focus on accessibility.",
      categories: ["Creativity", "E-Commerce"],
    },
    {
      id: 10,
      name: "Akash Verma",
      role: "Cybersecurity Analyst",
      location: "Pune",
      image: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=500&auto=format&fit=crop&q=60",
      skills: ["Penetration Testing", "Network Security", "Risk Analysis"],
      bio: "Securing digital infrastructures against evolving threats.",
      categories: ["Cyber Security", "Software"],
    },
    {
      id: 11,
      name: "Tanvi Desai",
      role: "Cloud Engineer",
      location: "Hyderabad",
      image: "https://images.unsplash.com/photo-1529636544492-9d950a944d9a?w=500&auto=format&fit=crop&q=60",
      skills: ["AWS", "Azure", "Kubernetes", "Terraform"],
      bio: "Building scalable and secure cloud architectures.",
      categories: ["Software", "Nonprofits"],
    },
    {
      id: 12,
      name: "Krishna Mehta",
      role: "Mobile App Developer",
      location: "Chennai",
      image: "https://images.unsplash.com/photo-1519638399535-1b036603ac77?w=500&auto=format&fit=crop&q=60",
      skills: ["Flutter", "React Native", "Swift", "Java"],
      bio: "Delivering intuitive and responsive mobile solutions.",
      categories: ["Education", "Travel"],
    },
    {
      id: 13,
      name: "Pooja Rao",
      role: "AI Researcher",
      location: "Goa",
      image: "https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=500&auto=format&fit=crop&q=60",
      skills: ["PyTorch", "Deep Learning", "Computer Vision", "NLP"],
      bio: "Advancing AI research with a focus on ethical applications.",
      categories: ["Artificial Intelligence", "Education"],
    },
    {
      id: 14,
      name: "Kartik Jain",
      role: "Game Developer",
      location: "Nagpur",
      image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=60",
      skills: ["Unity", "C#", "3D Modeling", "AR/VR"],
      bio: "Turning creative ideas into immersive gaming experiences.",
      categories: ["Creativity", "Marketing"],
    },
    {
      id: 15,
      name: "Anjali Kapoor",
      role: "Digital Marketer",
      location: "Noida",
      image: "https://images.unsplash.com/photo-1517430816045-df4b7de01f17?w=500&auto=format&fit=crop&q=60",
      skills: ["Google Ads", "Facebook Ads", "Analytics", "Email Marketing"],
      bio: "Helping brands reach their target audience effectively.",
      categories: ["Marketing", "Software"],
    },
    {
        id: 16,
        name: "Ritika Sharma",
        role: "DevOps Engineer",
        location: "Kolkata",
        image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&auto=format&fit=crop&q=60",
        skills: ["Docker", "Kubernetes", "CI/CD", "Linux"],
        bio: "Ensuring smooth and efficient delivery pipelines.",
        categories: ["Software", "Finance"],
      },
      {
        id: 17,
        name: "Aarav Malhotra",
        role: "Embedded Systems Engineer",
        location: "Jaipur",
        image: "https://images.unsplash.com/photo-1519358021765-5dba34da77ae?w=500&auto=format&fit=crop&q=60",
        skills: ["C", "Microcontrollers", "IoT", "RTOS"],
        bio: "Bringing hardware to life with innovative solutions.",
        categories: ["Education", "Creativity"],
      },
      {
        id: 18,
        name: "Sneha Roy",
        role: "Data Engineer",
        location: "Lucknow",
        image: "https://images.unsplash.com/photo-1550525811-e5869dd03032?w=500&auto=format&fit=crop&q=60",
        skills: ["SQL", "Big Data", "ETL", "Data Warehousing"],
        bio: "Building data pipelines for seamless analytics.",
        categories: ["Artificial Intelligence", "Travel"],
      },
      {
        id: 19,
        name: "Vikram Menon",
        role: "AR/VR Developer",
        location: "Kerala",
        image: "https://images.unsplash.com/photo-1497051788611-2c64812349ef?w=500&auto=format&fit=crop&q=60",
        skills: ["Unity", "Blender", "3D Animation", "C#"],
        bio: "Creating immersive AR/VR experiences for modern applications.",
        categories: ["Creativity", "Marketing"],
      },
      {
        id: 20,
        name: "Rajeev Nair",
        role: "System Administrator",
        location: "Coimbatore",
        image: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=500&auto=format&fit=crop&q=60",
        skills: ["Linux", "Networking", "Virtualization", "Security"],
        bio: "Maintaining robust IT infrastructures with efficiency.",
        categories: ["Software", "Nonprofits"],
      },
      {
        id: 21,
        name: "Isha Agarwal",
        role: "Technical Writer",
        location: "Patna",
        image: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=500&auto=format&fit=crop&q=60",
        skills: ["Documentation", "Content Writing", "SEO", "Research"],
        bio: "Converting complex technical concepts into user-friendly content.",
        categories: ["Education", "Marketing"],
      },
      {
        id: 22,
        name: "Kunal Das",
        role: "Machine Learning Engineer",
        location: "Guwahati",
        image: "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=500&auto=format&fit=crop&q=60",
        skills: ["Python", "Scikit-Learn", "TensorFlow", "NLP"],
        bio: "Turning data into intelligent solutions for real-world problems.",
        categories: ["Artificial Intelligence", "Finance"],
      },
      {
        id: 23,
        name: "Preeti Reddy",
        role: "HR Specialist",
        location: "Visakhapatnam",
        image: "https://images.unsplash.com/photo-1519638399535-1b036603ac77?w=500&auto=format&fit=crop&q=60",
        skills: ["Recruitment", "Team Building", "Conflict Management"],
        bio: "Connecting talent with opportunity to drive success.",
        categories: ["Nonprofits", "Education"],
      },
      {
        id: 24,
        name: "Tushar Gupta",
        role: "Network Engineer",
        location: "Indore",
        image: "https://images.unsplash.com/photo-1506812574058-fc75fa93fead?w=500&auto=format&fit=crop&q=60",
        skills: ["Cisco", "Switching", "Routing", "Security"],
        bio: "Optimizing network performance for seamless connectivity.",
        categories: ["Software", "Cyber Security"],
      },
      {
        id: 25,
        name: "Simran Kaur",
        role: "Social Media Manager",
        location: "Chandigarh",
        image: "https://images.unsplash.com/photo-1505033575518-a36ea2ef75ae?w=500&auto=format&fit=crop&q=60",
        skills: ["Content Creation", "Analytics", "Campaign Strategy"],
        bio: "Crafting engaging social media campaigns to grow brands.",
        categories: ["Marketing", "Creativity"],
      },
    // Add more users similarly up to 50
  ];
  