export const projectsData = [
  {
    id: 1,
    title: "A.I. X Automobile",
    description:
      "So there are some ideas in my mind but don't know exactly how to execute them. And if anyone has some more cool ideas about automobiles and AI then let's connect and transform the world of automobiles.",
    category: "AI/ML Specialist",
    teamSize: 1,
    createdBy: "@Kanhaiya Lal Sahu",
    createdAt:"10/11/2024",
    rolesAvailable: ["Web Developer","App Developer","Marketing"],
    teamMembers: [
      {
        name: "@Kanhaiya Sahu",
        role: "FOUNDER",
      },
      {
        name:"Venktesh badgaiyan",
        role:"Co-Founder"
      }
    ],
    statusTags: ["IDEA", "COFOUNDING"],
    tags: [
      "Artificial Intelligence",
      "Machine Learning",
      "Autonomous Vehicles",
      "Computer Vision",
      "Deep Learning",
      "IoT",
      "Edge Computing",
      "AI Ethics",
      "Automotive Tech",
      "Data Analysis",
    ],
    imageSrc:
      "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dGVjaG5vbG9neXxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 2,
    title: "Snap Style",
    description:
      "An app for fashion enthusiasts who love to showcase their unique style! Effortlessly add your favorite brand's logo to your images and make your outfits stand out.",
    category: "Frontend Developer",
    teamSize: 3,
    createdBy: "@Venketesh ",
    rolesAvailable: "Designers",
    teamMembers: [
      {
        name: "@Bhavin_Khunt",
        role: "FOUNDER",
      },
      {
        name: "@Sara_Jones",
        role: "Designer",
      },
      {
        name: "@Michael_Liu",
        role: "Developer",
      },
    ],
    statusTags: ["ACTIVE", "LOOKING FOR TEAM"],
    tags: [
      "Frontend Development",
      "Mobile App Development",
      "Image Processing",
      "React Native",
      "UI/UX Design",
      "AR/VR",
      "Web Technologies",
      "Graphics Design",
      "Brand Integration",
      "Responsive Design",
    ],
    imageSrc:
      "https://plus.unsplash.com/premium_photo-1681399975135-252eab5fd2db?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dGVjaG5vbG9neXxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 3,
    title: "EduTech Boost",
    description:
      "Creating a platform that integrates AI with educational tools to provide personalized learning experiences for students worldwide.",
    category: "Full Stack Developer",
    teamSize: 2,
    createdBy: "@JohnDoe",
    rolesAvailable: "Developers",
    teamMembers: [
      {
        name: "@JohnDoe",
        role: "FOUNDER",
      },
      {
        name: "@JaneSmith",
        role: "Educator",
      },
    ],
    statusTags: ["IDEA", "FUNDRAISING"],
    tags: [
      "EdTech",
      "AI in Education",
      "E-Learning Platforms",
      "Personalized Learning",
      "Natural Language Processing",
      "Cloud Computing",
      "Backend Development",
      "Frontend Development",
      "Mobile Learning",
      "Gamified Learning",
    ],
    imageSrc:
      "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRlY2hub2xvZ3l8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 4,
    title: "GreenScape AI",
    description:
      "Leveraging AI to analyze environmental data and suggest actionable solutions for urban green initiatives and climate impact reduction.",
    category: "Data Scientist",
    teamSize: 4,
    createdBy: "@EcoWarrior",
    rolesAvailable: "Data Analysts",
    teamMembers: [
      {
        name: "@EcoWarrior",
        role: "FOUNDER",
      },
      {
        name: "@GreenExpert",
        role: "Environmentalist",
      },
      {
        name: "@DevDrew",
        role: "Developer",
      },
      {
        name: "@AI_Mike",
        role: "AI Specialist",
      },
    ],
    statusTags: ["ACTIVE", "COFOUNDING"],
    tags: [
      "Environmental Tech",
      "AI in Environment",
      "Data Analytics",
      "Climate Change",
      "Sustainability",
      "Big Data",
      "Predictive Analytics",
      "GIS Mapping",
      "Green Technology",
      "Urban Planning",
    ],
    imageSrc:
      "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHRlY2hub2xvZ3l8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 5,
    title: "FoodPal AI",
    description:
      "Revolutionizing meal planning with an AI-driven app that provides personalized recipes and grocery lists based on dietary needs and preferences.",
    category: "MERN Stack Developer",
    teamSize: 3,
    createdBy: "@HealthyChef",
    rolesAvailable: "Nutritionists",
    teamMembers: [
      {
        name: "@HealthyChef",
        role: "FOUNDER",
      },
      {
        name: "@CodeSam",
        role: "Developer",
      },
      {
        name: "@UX_Lucy",
        role: "UI/UX Designer",
      },
    ],
    statusTags: ["ACTIVE", "TESTING"],
    tags: [
      "AI for Lifestyle",
      "MERN Stack",
      "AI Meal Planning",
      "HealthTech",
      "API Integration",
      "UI/UX Design",
      "Data Visualization",
      "App Development",
      "Cloud Hosting",
      "Nutrition Tech",
    ],
    imageSrc:
      "https://plus.unsplash.com/premium_photo-1683121710572-7723bd2e235d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fHRlY2hub2xvZ3l8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 6,
    title: "Smart Farm Network",
    description:
      "Building a platform that connects farmers with AI tools for crop management, weather predictions, and pest control to enhance agricultural productivity.",
    category: "Backend Developer",
    teamSize: 5,
    createdBy: "@AgroTech_Pro",
    rolesAvailable: "Agricultural Scientists",
    teamMembers: [
      { name: "@AgroTech_Pro", role: "FOUNDER" },
      { name: "@FarmExpert", role: "Farmer" },
      { name: "@DataDee", role: "Data Scientist" },
      { name: "@AI_Lab", role: "AI Developer" },
      { name: "@DesignAlex", role: "Designer" },
    ],
    statusTags: ["IDEA", "COFOUNDING"],
    imageSrc: "https://plus.unsplash.com/premium_photo-1661963874418-df1110ee39c1?w=500&auto=format&fit=crop&q=60",
    tags: [
      "Agritech", 
      "AI Solutions", 
      "Machine Learning", 
      "Backend Development", 
      "Crop Management", 
      "Sustainable Tech", 
      "IoT in Agriculture", 
      "Big Data", 
      "Precision Farming", 
      "Weather Prediction",
    ],
  },
  {
    id: 7,
    title: "Travelify",
    description:
      "An AI travel assistant that plans trips, books flights, and provides real-time suggestions for activities based on traveler preferences.",
    category: "Technology",
    teamSize: 2,
    createdBy: "@TravelGuru",
    rolesAvailable: "Marketers",
    teamMembers: [
      { name: "@TravelGuru", role: "FOUNDER" },
      { name: "@CodeChris", role: "Developer" },
    ],
    statusTags: ["BETA", "MARKET LAUNCH"],
    imageSrc: "https://plus.unsplash.com/premium_photo-1681400054984-c20bf5879c3b?w=500&auto=format&fit=crop&q=60",
    tags: [
      "Travel Tech", 
      "AI Solutions", 
      "Personalization", 
      "Natural Language Processing", 
      "Web Development", 
      "Real-Time Suggestions", 
      "Data Analysis", 
      "Automation", 
      "APIs Integration", 
      "ReactJS",
    ],
  },
  {
    id: 8,
    title: "FinAIce",
    description:
      "Developing a user-friendly AI assistant for financial planning and investment strategies to help individuals manage their money more effectively.",
    category: "Technology",
    teamSize: 3,
    createdBy: "@FinanceExpert",
    rolesAvailable: "Finance Experts",
    teamMembers: [
      { name: "@FinanceExpert", role: "FOUNDER" },
      { name: "@MoneyMax", role: "Economist" },
      { name: "@DevAsha", role: "Developer" },
    ],
    statusTags: ["FUNDRAISING", "COFOUNDING"],
    imageSrc: "https://plus.unsplash.com/premium_photo-1681398842383-25f5613873b1?w=500&auto=format&fit=crop&q=60",
    tags: [
      "FinTech", 
      "AI Solutions", 
      "Finance Automation", 
      "Backend Development", 
      "Investment Strategies", 
      "Data Science", 
      "APIs Integration", 
      "Predictive Analytics", 
      "Security Systems", 
      "User Experience",
    ],
  },
  {
    id: 9,
    title: "HealthHub AI",
    description:
      "Creating a centralized healthcare platform powered by AI to provide personalized health advice and real-time monitoring for patients.",
    category: "Data Scientist",
    teamSize: 4,
    createdBy: "@HealthGeek",
    rolesAvailable: "Healthcare Specialists",
    teamMembers: [
      { name: "@HealthGeek", role: "FOUNDER" },
      { name: "@TechyMed", role: "AI Specialist" },
      { name: "@CodeDoc", role: "Developer" },
      { name: "@DataAnalyzer", role: "Data Scientist" },
    ],
    statusTags: ["PROTOTYPE", "TESTING"],
    imageSrc: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRlY2hub2xvZ3l8ZW58MHx8MHx8fDA%3D",
    tags: [
      "Healthcare Tech", 
      "AI Solutions", 
      "Health Monitoring", 
      "Real-Time Analytics", 
      "Data Science", 
      "IoT Integration", 
      "APIs Integration", 
      "AI Models", 
      "Cloud Solutions", 
      "Data Visualization",
    ],
  },
  {
    id: 10,
    title: "CodeTutor AI",
    description:
      "Developing an AI-powered learning assistant for coders to provide instant feedback, debugging suggestions, and personalized learning resources.",
    category: "Full Stack Developer",
    teamSize: 3,
    createdBy: "@CodeMaster",
    rolesAvailable: "Educators",
    teamMembers: [
      { name: "@CodeMaster", role: "FOUNDER" },
      { name: "@DevChris", role: "Frontend Developer" },
      { name: "@AI_Pro", role: "AI Specialist" },
    ],
    statusTags: ["BETA", "TESTING"],
    imageSrc: "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHRlY2hub2xvZ3l8ZW58MHx8MHx8fDA%3D",
    tags: [
      "EdTech", 
      "AI Solutions", 
      "Machine Learning", 
      "Code Debugging", 
      "Frontend Development", 
      "Natural Language Processing", 
      "Learning Tools", 
      "ReactJS", 
      "APIs Integration", 
      "Real-Time Suggestions",
    ],
  },
  
];
